import type { Race } from './races';

export const liveRaces: Race[] = [
  {
    id: 'live-1',
    name: 'Bán kết — Vòng 1',
    number: 3,
    status: 'live',
    date: '2026-06-04',
    time: '15:30',
    location: 'Giải Đua Mùa Xuân 2026',
    surface: 'Cỏ',
    track: 'Oval',
    distance: 1800,
    laps: 2,
    purse: 600_000_000,
    entries: [
      { horse: { id: 'lh1',  name: 'Thiên Lôi',   number: 1,  breed: 'Thoroughbred',  color: '#FFB86C' }, jockeyName: 'Nguyễn Minh Tuấn', odds: 2.1 },
      { horse: { id: 'lh2',  name: 'Gió Đông',    number: 4,  breed: 'Arabian',        color: '#72D79A' }, jockeyName: 'Trần Anh Hùng',    odds: 3.0 },
      { horse: { id: 'lh3',  name: 'Rồng Đỏ',     number: 6,  breed: 'Thoroughbred',  color: '#FF6B6B' }, jockeyName: 'Lê Văn Khoa',       odds: 3.8 },
      { horse: { id: 'lh4',  name: 'Bạch Long',   number: 2,  breed: 'Warmblood',      color: '#B2BEC3' }, jockeyName: 'Vũ Quang Huy',      odds: 5.2 },
      { horse: { id: 'lh5',  name: 'Hắc Phong',   number: 8,  breed: 'Quarter Horse', color: '#636E72' }, jockeyName: 'Phạm Bình Nam',     odds: 6.0 },
      { horse: { id: 'lh6',  name: 'Kim Long',     number: 5,  breed: 'Arabian',        color: '#F0932B' }, jockeyName: 'Đỗ Hải Long',       odds: 7.5 },
      { horse: { id: 'lh7',  name: 'Tử Điện',     number: 7,  breed: 'Thoroughbred',  color: '#6C5CE7' }, jockeyName: 'Hoàng Văn Mạnh',    odds: 8.5 },
      { horse: { id: 'lh8',  name: 'Ngọc Phong',  number: 9,  breed: 'Warmblood',      color: '#A29BFE' }, jockeyName: 'Đinh Văn Tú',       odds: 10.0 },
      { horse: { id: 'lh9',  name: 'Xuân Phong',  number: 3,  breed: 'Arabian',        color: '#55EFC4' }, jockeyName: 'Phan Minh Nhật',    odds: 12.0 },
      { horse: { id: 'lh10', name: 'Băng Tuyết',  number: 10, breed: 'Quarter Horse', color: '#74B9FF' }, jockeyName: 'Cao Việt Anh',      odds: 14.0 },
    ],
  },
  {
    id: 'live-2',
    name: 'Bán kết — Vòng 2',
    number: 4,
    status: 'live',
    date: '2026-06-04',
    time: '16:00',
    location: 'Giải Đua Mùa Xuân 2026',
    surface: 'Cỏ',
    track: 'Oval',
    distance: 1800,
    laps: 2,
    purse: 600_000_000,
    entries: [
      { horse: { id: 'lh11', name: 'Thần Tốc',    number: 3,  breed: 'Thoroughbred',  color: '#FDCB6E' }, jockeyName: 'Mai Xuân Trường',   odds: 2.3 },
      { horse: { id: 'lh12', name: 'Lửa Hồng',    number: 7,  breed: 'Thoroughbred',  color: '#E17055' }, jockeyName: 'Dương Quang Hải',   odds: 3.2 },
      { horse: { id: 'lh13', name: 'Ngân Tiêu',   number: 1,  breed: 'Arabian',        color: '#A0C4FF' }, jockeyName: 'Trương Văn Đức',    odds: 4.0 },
      { horse: { id: 'lh14', name: 'Phi Vũ',       number: 9,  breed: 'Quarter Horse', color: '#4ECDC4' }, jockeyName: 'Lâm Thành Đạt',    odds: 5.5 },
      { horse: { id: 'lh15', name: 'Mộng Long',   number: 5,  breed: 'Warmblood',      color: '#FD79A8' }, jockeyName: 'Bùi Văn Long',      odds: 6.8 },
      { horse: { id: 'lh16', name: 'Sấm Vàng',    number: 2,  breed: 'Thoroughbred',  color: '#F9CA24' }, jockeyName: 'Nguyễn Hữu Phúc',  odds: 7.8 },
      { horse: { id: 'lh17', name: 'Đại Bàng',    number: 6,  breed: 'Arabian',        color: '#E84393' }, jockeyName: 'Vũ Thành Nam',      odds: 9.0 },
      { horse: { id: 'lh18', name: 'Sóng Thần',   number: 8,  breed: 'Warmblood',      color: '#0984E3' }, jockeyName: 'Đỗ Minh Khoa',     odds: 10.5 },
      { horse: { id: 'lh19', name: 'Hỏa Long',    number: 4,  breed: 'Quarter Horse', color: '#D63031' }, jockeyName: 'Mai Xuân Trường',   odds: 12.5 },
      { horse: { id: 'lh20', name: 'Tinh Vân',    number: 10, breed: 'Arabian',        color: '#00CEC9' }, jockeyName: 'Đinh Văn Tú',       odds: 14.0 },
    ],
  },
];
